[program:laravel-horizon]
process_name=%(program_name)s
command=php /var/www/artisan horizon
autostart=true
autorestart=true
startretries=5
user=project-user
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/laravel-horizon.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stopasgroup=true
killasgroup=true
stopwaitsecs=3600
